FROM mhart/alpine-node:8.9.1

RUN apk add --no-cache git

RUN npm install pm2 -g

ADD package-lock.json package.json /tmp/
RUN cd /tmp && npm install
RUN mkdir -p /usr/src/app && cp -a /tmp/node_modules /usr/src/app/

WORKDIR /usr/src/app

COPY . /usr/src/app

EXPOSE 1999

CMD ["pm2", "start", "relay.json", "--no-daemon"]
